"""empty message

Revision ID: 35d2b2f50c57
Revises: 
Create Date: 2025-08-24 18:52:03.365259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35d2b2f50c57'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_ties_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('change_type', sa.String(length=6), nullable=False),
    sa.Column('change_date', sa.DateTime(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.Column('change_user_id', sa.String(length=100), nullable=False),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.Column('article_tie_original_article_id', sa.Integer(), nullable=False),
    sa.Column('article_tie_followup_article_id', sa.Integer(), nullable=False),
    sa.Column('similarity', sa.Numeric(precision=10, scale=10), nullable=True),
    sa.Column('manually_set', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('articles_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('change_type', sa.String(length=6), nullable=False),
    sa.Column('change_date', sa.DateTime(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.Column('change_user_id', sa.String(length=100), nullable=False),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('feed_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=4000), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('full_text', sa.Text(), nullable=True),
    sa.Column('published', sa.DateTime(), nullable=True),
    sa.Column('following', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feeds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=4000), nullable=False),
    sa.Column('last_fetch', sa.DateTime(), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('deleted', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feeds_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('change_type', sa.String(length=6), nullable=False),
    sa.Column('change_date', sa.DateTime(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.Column('change_user_id', sa.String(length=100), nullable=False),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.Column('feed_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('url', sa.String(length=4000), nullable=True),
    sa.Column('last_fetch', sa.DateTime(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('labels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('text', sa.String(length=100), nullable=False),
    sa.Column('hypothesis', sa.String(length=100), nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('labels_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('change_type', sa.String(length=6), nullable=False),
    sa.Column('change_date', sa.DateTime(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.Column('change_user_id', sa.String(length=100), nullable=False),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.Column('label_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=100), nullable=True),
    sa.Column('hypothesis', sa.String(length=100), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scored_labels_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('change_type', sa.String(length=6), nullable=False),
    sa.Column('change_date', sa.DateTime(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.Column('change_user_id', sa.String(length=100), nullable=False),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.Column('scored_label_article_id', sa.Integer(), nullable=False),
    sa.Column('scored_label_label_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Numeric(precision=10, scale=10), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scored_topics_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('change_type', sa.String(length=6), nullable=False),
    sa.Column('change_date', sa.DateTime(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.Column('change_user_id', sa.String(length=100), nullable=False),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.Column('scored_topic_article_id', sa.Integer(), nullable=False),
    sa.Column('scored_topic_topic_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Numeric(precision=10, scale=10), nullable=True),
    sa.Column('manually_set', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('change_type', sa.String(length=6), nullable=False),
    sa.Column('change_date', sa.DateTime(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.Column('change_user_id', sa.String(length=100), nullable=False),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.Column('tag_article_id', sa.Integer(), nullable=False),
    sa.Column('tag_topic_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Numeric(precision=10, scale=10), nullable=True),
    sa.Column('manually_set', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topic_labels_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('change_type', sa.String(length=6), nullable=False),
    sa.Column('change_date', sa.DateTime(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.Column('change_user_id', sa.String(length=100), nullable=False),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.Column('topic_label_topic_id', sa.Integer(), nullable=False),
    sa.Column('topic_label_label_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Numeric(precision=10, scale=10), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_global', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('deleted', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topics_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('change_type', sa.String(length=6), nullable=False),
    sa.Column('change_date', sa.DateTime(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.Column('change_user_id', sa.String(length=100), nullable=False),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('is_global', sa.Boolean(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guid', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=100), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('change_type', sa.String(length=6), nullable=False),
    sa.Column('change_date', sa.DateTime(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.Column('change_user_id', sa.String(length=100), nullable=False),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('guid', sa.String(length=100), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('hashed_password', sa.String(length=100), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('articles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('feed_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=4000), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('full_text', sa.Text(), nullable=True),
    sa.Column('published', sa.DateTime(), nullable=False),
    sa.Column('following', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('deleted', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['feed_id'], ['feeds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topic_labels',
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('label_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Numeric(precision=10, scale=10), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['label_id'], ['labels.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('topic_id', 'label_id')
    )
    op.create_table('article_ties',
    sa.Column('original_article_id', sa.Integer(), nullable=False),
    sa.Column('followup_article_id', sa.Integer(), nullable=False),
    sa.Column('similarity', sa.Numeric(precision=10, scale=10), nullable=True),
    sa.Column('manually_set', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('deleted', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['followup_article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['original_article_id'], ['articles.id'], ),
    sa.PrimaryKeyConstraint('original_article_id', 'followup_article_id')
    )
    op.create_table('scored_labels',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('label_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Numeric(precision=10, scale=10), nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['label_id'], ['labels.id'], ),
    sa.PrimaryKeyConstraint('article_id', 'label_id')
    )
    op.create_table('scored_topics',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Numeric(precision=10, scale=10), nullable=True),
    sa.Column('manually_set', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('deleted', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('article_id', 'topic_id')
    )
    op.create_table('tags',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Numeric(precision=10, scale=10), server_default=sa.text('(1.0)'), nullable=True),
    sa.Column('manually_set', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('deleted', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('article_id', 'topic_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tags')
    op.drop_table('scored_topics')
    op.drop_table('scored_labels')
    op.drop_table('article_ties')
    op.drop_table('topic_labels')
    op.drop_table('articles')
    op.drop_table('users_history')
    op.drop_table('users')
    op.drop_table('topics_history')
    op.drop_table('topics')
    op.drop_table('topic_labels_history')
    op.drop_table('tags_history')
    op.drop_table('scored_topics_history')
    op.drop_table('scored_labels_history')
    op.drop_table('labels_history')
    op.drop_table('labels')
    op.drop_table('feeds_history')
    op.drop_table('feeds')
    op.drop_table('articles_history')
    op.drop_table('article_ties_history')
    # ### end Alembic commands ###
