"""empty message

Revision ID: 5e03344d7e87
Revises: e12bffda051e
Create Date: 2025-09-03 20:18:57.775654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e03344d7e87'
down_revision = 'e12bffda051e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        CREATE VIEW view_scored_label_topics AS
        SELECT
            sl.article_id,
            sl.label_id,
            st.topic_id,
            tl.weight AS topic_label_weight
        FROM scored_labels sl
        JOIN topic_labels tl ON sl.label_id = tl.label_id
        JOIN scored_topics st ON st.topic_id = tl.topic_id AND st.article_id = sl.article_id
        WHERE tl.enabled = 1;
    """)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP VIEW view_scored_label_topics')
    # ### end Alembic commands ###
